### ISSUE TITLE
Error in loading

### ISSUE THREAD

**Issue by infiniteschema** [rgrp/csv2sqlite#14]
First, thanks for the great script. I'm experiencing an error loading the following file (remove .txt extension):
[products-test.csv.txt](https://github.com/rgrp/csv2sqlite/files/50643/products-test.csv.txt)

The error is:
```
Traceback (most recent call last):
  File "./csv2sqlite.py", line 185, in <module>
    convert(args.csv_file, args.sqlite_db_file, args.table_name, args.headers, compression)
  File "./csv2sqlite.py", line 53, in convert
    types = _guess_types(type_reader, len(headers))
  File "./csv2sqlite.py", line 142, in _guess_types
    results[column][data_type] += 1
IndexError: list index out of range
```

Error occurs on the last line of data. If you remove it, it works perfectly. Could it be due to commas in one of the text fields? Thanks in advance for your help.

**Comment by rgrp** [comment]
@infiniteschema can you post the last line of your data as raw CSV so we can look at it ...

**Comment by infiniteschema** [comment]
@rgrp hi, yes, I posted the CSV in the initial post - did you see it? products-test.csv.txt, but remove .txt extension (had to be uploaded as .txt file). There are only 2 lines of data, the first works fine, the last does not...

**Comment by rgrp** [comment]
@infiniteschema sorry - i missed this at the time. Is is not working?

**Comment by miketahani** [comment]
I'm also having this problem. I added this after line 148:

``` python
print('row_index: {}, len(row): {} '.format(row_index, len(row)))
```

and got this output:

```
row_index: 0, len(row): 280
row_index: 1, len(row): 280
row_index: 2, len(row): 280
...
row_index: 5175, len(row): 280
row_index: 5176, len(row): 280
row_index: 5177, len(row): 281
```
