### ISSUE TITLE
Floats being converted to integer (Unable to convert value)

### ISSUE THREAD

**Issue by ryanjones** [rgrp/csv2sqlite#18]
I tried running this to create an SQLite DB from a CSV, but I'm getting this error for all of my floats (negative and positive). 

Unable to convert value '39.99' to type 'integer' on line 5304

Here's an example of the row:
```
2016-01-07 0:00,	16:15,	56: Edmonton Manning,	test,	test213,	test111,	0,	39.99,	<Unknown>,	<Unknowon>,		<Unknown>,	<Unknown>,	
```

I'll try and dig into the issue, but my python isn't very strong, any help would be much appreciated.

**Comment by rgrp** [comment]
@ryanjones thanks for the report and glad you find this library useful. What's happening here is that the library has misguessed one of your columns as integers when in fact it is a float/decimal. My guess is that the first 1000 or so lines or your data (which we use for type guessing) only has stuff in that column that looks like integers.

One way to fix this is to explicitly set the types as per #16 - or you could even use a more powerful library and setup using JSON Table Schema - see http://frictionlessdata.io/guides/json-table-schema/

**Comment by AlainFELER** [comment]
Hello, I'm trying to use de --types option : --types zzz.csv with zzz.csv containing
string,real,string,string,string,string,string,string
but all I get is an error which I am unable to fix :  
python csv2sqlite.py --types zzz.csv zAF_UTF8.csv base.sqlite DEM
Traceback (most recent call last):
  File "csv2sqlite.py", line 207, in <module>
    convert(args.csv_file, args.sqlite_db_file, args.table_name, args.headers, compression, args.types)
  File "csv2sqlite.py", line 69, in convert
    to.close()
AttributeError: 'list' object has no attribute 'close'
---
I get the same error with zzz.csv =
"string","real","string","string","string","string","string","string"
or 
string;real;string;string;string;string;string;string
or 
"string";"real";"string";"string";"string";"string";"string";"string"
---
Thank you in advance for the help.

**Comment by rgrp** [comment]
INVALID. Closing for now as I think we have the answer. @ryanjones feel free to re-open if you differ on this ;-)
